### ISSUE TITLE
Training model

### ISSUE THREAD

**Issue by xovobobo** [ika-rwth-aachen/EviLOG#15]

**Comment by RaphvK** [comment]
Yes, you can use the `--model-weights` argument with the training script, e.g.:

`./train.py -c config.yml --model-weights output/<YOUR-TIMESTAMP>/Checkpoints/best_weights.hdf5`

**Comment by xovobobo** [comment]
> Yes, you can use the `--model-weights` argument with the training script, e.g.:
> 
> `./train.py -c config.yml --model-weights output/<YOUR-TIMESTAMP>/Checkpoints/best_weights.hdf5`

thx
