### ISSUE TITLE
how to change view angle?

### ISSUE THREAD

**Issue by Ykrowa** [ika-rwth-aachen/EviLOG#17]
Is it possible to change the view angle? By default its 360 degreeds, but my lidar has only 120 degreeds

**Comment by RaphvK** [comment]
In theory, this should be possible. You could modify the content of `lidar` after [this line](https://github.com/ika-rwth-aachen/EviLOG/blob/d35bf4fb01e576d3260f152a59221218190b1981/model/train.py#L214) and eliminate all points outside the 120 deg field of view during training.
