### ISSUE TITLE
 Hello, can I get your EviLOG data set? This is my email 3108096685@qq.com, looking forward to your reply!

### ISSUE THREAD

**Issue by 3oo0q-kvmlskz** [ika-rwth-aachen/EviLOG#19]
Hello, can I get your EviLOG data set?
This is my email [3108096685@qq.com](mailto:3108096685@qq.com), looking forward to your reply!

**Comment by chan-yuu** [comment]
> Hello, can I get your EviLOG data set? This is my email [3108096685@qq.com](mailto:3108096685@qq.com), looking forward to your reply!

Do you have the data now? Can you share the training data？

**Comment by RaphvK** [comment]
> > Hello, can I get your EviLOG data set? This is my email [3108096685@qq.com](mailto:3108096685@qq.com), looking forward to your reply!
> 
> Do you have the data now? Can you share the training data？

Please follow the instructions [here](https://github.com/ika-rwth-aachen/EviLOG#data) to obtain the dataset. Further distribution to third-parties is not allowed.

**Comment by chan-yuu** [comment]
> > > Hello, can I get your EviLOG data set? This is my email [3108096685@qq.com](mailto:3108096685@qq.com), looking forward to your reply!
> > 
> > Do you have the data now? Can you share the training data？
> 
> Please follow the instructions [here](https://github.com/ika-rwth-aachen/EviLOG#data) to obtain the dataset. Further distribution to third-parties is not allowed.

Hi, I sent you an email a days ago asking for the training data, but I haven’t received a reply yet. Could you please help me and send it to me as soon as possible? Thank you very much.

**Comment by RaphvK** [comment]
> > > > Hello, can I get your EviLOG data set? This is my email [3108096685@qq.com](mailto:3108096685@qq.com), looking forward to your reply!
> > > 
> > > 
> > > Do you have the data now? Can you share the training data？
> > 
> > 
> > Please follow the instructions [here](https://github.com/ika-rwth-aachen/EviLOG#data) to obtain the dataset. Further distribution to third-parties is not allowed.
> 
> Hi, I sent you an email a days ago asking for the training data, but I haven’t received a reply yet. Could you please help me and send it to me as soon as possible? Thank you very much.

You're right, unfortunately your email was classified as spam by our system. I just sent you a link to the dataset.

**Comment by chan-yuu** [comment]
> > > > > Hello, can I get your EviLOG data set? This is my email [3108096685@qq.com](mailto:3108096685@qq.com), looking forward to your reply!
> > > > 
> > > > 
> > > > Do you have the data now? Can you share the training data？
> > > 
> > > 
> > > Please follow the instructions [here](https://github.com/ika-rwth-aachen/EviLOG#data) to obtain the dataset. Further distribution to third-parties is not allowed.
> > 
> > 
> > Hi, I sent you an email a days ago asking for the training data, but I haven’t received a reply yet. Could you please help me and send it to me as soon as possible? Thank you very much.
> 
> You're right, unfortunately your email was classified as spam by our system. I just sent you a link to the dataset.

Okay, I received it. Thanks a lot.
